# Generated by Django 4.1.7 on 2023-07-05 05:55

from django.db import migrations, models
import utils.models.models_fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogposts",
            name="author",
        ),
        migrations.AlterField(
            model_name="blogposts",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dxs0fol71/image/upload/v1688536246/afe66629b25b6b778e46800144e13a7e_v9mnps.jpg",
                null=True,
                upload_to=utils.models.models_fields.img_dir_path,
            ),
        ),
        migrations.AlterField(
            model_name="myproject",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dxs0fol71/image/upload/v1688536246/afe66629b25b6b778e46800144e13a7e_v9mnps.jpg",
                null=True,
                upload_to=utils.models.models_fields.img_dir_path,
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
