# Generated by Django 4.1.7 on 2023-07-05 10:28

from django.db import migrations, models
import utils.models.models_fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_blogposts_author_alter_blogposts_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogposts",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dxs0fol71/image/upload/v1688536246/afe66629b25b6b778e46800144e13a7e_v9mnps.jpg",
                max_length=1000,
                upload_to=utils.models.models_fields.img_dir_path,
            ),
        ),
        migrations.AlterField(
            model_name="myproject",
            name="image",
            field=models.ImageField(
                default="https://res.cloudinary.com/dxs0fol71/image/upload/v1688536246/afe66629b25b6b778e46800144e13a7e_v9mnps.jpg",
                max_length=1000,
                upload_to=utils.models.models_fields.img_dir_path,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
        ),
    ]
