# Generated by Django 4.1.7 on 2023-07-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_blogposts_image_alter_myproject_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceTrack",
        ),
    ]
